server:
  port: 8808
  context-path: /msg
  jsp-servlet:
    init-parameters:
      developments: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.0.251:3306/student?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  mvc:
    view:
      prefix: /
      suffix: .jsp
mybatis:
  mapper-locations: classpath:com/baizhi/lpm/mapper/*Mapper.xml
  type-aliases-package: com.baizhi.lpm.entity